ci: clean pipeline

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -16,26 +16,26 @@ variables:
   DOCKERHUB_CORE_REPO: cytomine/core
   DOCKER_TMP_IMAGE_NAME: $CI_PIPELINE_ID:latest
   DOCKER_TMP_JAR_IMAGE_NAME: $CI_PIPELINE_ID-jar-builder:latest
-  
+
 # variable to register in project:
 # - DOCKERHUB_URL: url of dockerhub (e.g. docker.io)
 # - DOCKERHUB_USER: cytomine username on dockerhub
 # - DOCKERHUB_PASSWORD: cytomine password on dockerhub
-# - SCRIPTS_REPO_ACCESS_TOKEN_NAME: access token name for docker-entrypoint-scripts repo 
+# - SCRIPTS_REPO_ACCESS_TOKEN_NAME: access token name for docker-entrypoint-scripts repo
 # - SCRIPTS_REPO_ACCESS_TOKEN_VALUE: access token value for docker-entrypoint-scripts repo
-# - SCRIPTS_REPO_URL: git url (no scheme/protocol) of the docker-entrypoint-scripts repo  
+# - SCRIPTS_REPO_URL: git url (no scheme/protocol) of the docker-entrypoint-scripts repo
 
 default:
-  tags: 
+  tags:
     - docker
 
 workflow:
   rules:
     - if: $CI_COMMIT_TAG != null && $CI_COMMIT_TAG =~ /^ce-.*$/
-      variables: 
+      variables:
         IS_OPEN_SOURCE_RELEASE_CANDIDATE: "true"
     - if: $CI_COMMIT_TAG == null || $CI_COMMIT_REF_NAME !~ /^ce-.*$/
-      variables: 
+      variables:
         IS_OPEN_SOURCE_RELEASE_CANDIDATE: "false"
     - when: always
 
@@ -51,8 +51,8 @@ make-version-name:
       fi
     - cat .env
   artifacts:
-    paths:
-      - .env
+    reports:
+      dotenv: .env
 
 run-junit:
   stage: test
@@ -69,8 +69,8 @@ run-junit:
     - sed -i -- "s/localhost:5433/postgres:5432/g" src/test/resources/application.yml
     - "sed -i -- 's/host: 127.0.0.1/host: mongodb/g' src/test/resources/application.yml"
     - "sed -i -- 's/port: 27018/port: 27017/g' src/test/resources/application.yml"
-    # test log too large for gitlab if executed at 'debug' log level 
-    - sed -i -- "s/name=\"be.cytomine\" level=\"debug\"/name=\"be.cytomine\" level=\"info\"/g" src/test/resources/logback-test.xml  
+    # test log too large for gitlab if executed at 'debug' log level
+    - sed -i -- "s/name=\"be.cytomine\" level=\"debug\"/name=\"be.cytomine\" level=\"info\"/g" src/test/resources/logback-test.xml
     - gradle :test --no-daemon
   artifacts:
     reports:
@@ -83,24 +83,23 @@ build-jar:
   rules:
     - if: $CI_COMMIT_TAG
   needs:
-    # no dependence on junit tests success. This allow for build 
-    # stage jobs to run in parallel with tests. If test fails, 
-    # publish jobs are aborted  
+    # no dependence on junit tests success. This allow for build
+    # stage jobs to run in parallel with tests. If test fails,
+    # publish jobs are aborted
     - job: make-version-name
       artifacts: true
   script:
-    - source .env
-    - docker build --build-arg CORE_VERSION=${CM_VERSION} -t $DOCKER_TMP_JAR_IMAGE_NAME -f docker/Dockerfile --target jar-builder .
+    - docker build --build-arg CORE_VERSION=$CM_VERSION -t $DOCKER_TMP_JAR_IMAGE_NAME -f docker/Dockerfile --target jar-builder .
     - docker run --name $CI_PIPELINE_ID-builder-container -t $DOCKER_TMP_JAR_IMAGE_NAME
     - mkdir -p build/libs/
     - docker cp $CI_PIPELINE_ID-builder-container:/app/build/libs/cytomine.jar build/libs/cytomine-$CM_VERSION.jar
   after_script:
-    - docker rm $CI_PIPELINE_ID-builder-container
+    - docker rm $CI_PIPELINE_ID-builder-container || true
     - docker rmi $DOCKER_TMP_JAR_IMAGE_NAME
   artifacts:
     when: on_success
     expire_in: never
-    paths: 
+    paths:
       - build/libs/cytomine-*.jar
 
 build-docker-image:
@@ -114,11 +113,10 @@ build-docker-image:
   rules:
     - if: $CI_COMMIT_TAG
   script:
-    - source .env
-    - export SCRIPTS_REPO_FULL_URL=https://${SCRIPTS_REPO_ACCESS_TOKEN_NAME}:${SCRIPTS_REPO_ACCESS_TOKEN_VALUE}@${SCRIPTS_REPO_URL}
-    - docker build --build-arg CORE_VERSION=${CM_VERSION} --build-arg SCRIPTS_REPO_TAG=latest --secret id=scripts_repo_url,env=SCRIPTS_REPO_FULL_URL -t $DOCKER_TMP_IMAGE_NAME -f docker/Dockerfile .
+    - export SCRIPTS_REPO_FULL_URL=https://$SCRIPTS_REPO_ACCESS_TOKEN_NAME:$SCRIPTS_REPO_ACCESS_TOKEN_VALUE@$SCRIPTS_REPO_URL
+    - docker build --build-arg CORE_VERSION=$CM_VERSION --build-arg SCRIPTS_REPO_TAG=latest --secret id=scripts_repo_url,env=SCRIPTS_REPO_FULL_URL -t $DOCKER_TMP_IMAGE_NAME -f docker/Dockerfile .
 
-publish-docker-image: 
+publish-docker-image:
   stage: publish
   image: docker:latest
   needs:
@@ -131,22 +129,21 @@ publish-docker-image:
   rules:
     - if: $CI_COMMIT_TAG
   script:
-    - source .env
     - |
       if [ $IS_OPEN_SOURCE_RELEASE_CANDIDATE = "true" ]; then
-        echo "Open-source release candidate (=$IS_OPEN_SOURCE_RELEASE_CANDIDATE) > push image to DockerHub"
+        echo "Open-source release candidate > push image to DockerHub"
         export DOCKER_IMAGE_NAME=cytomine/core
         export TARGET_CI_REGISTRY=$DOCKERHUB_URL
         export TARGET_CI_REGISTRY_USER=$DOCKERHUB_USER
         export TARGET_CI_REGISTRY_PASSWORD=$DOCKERHUB_PASSWORD
       else
-        echo "Closed-source release candidate (=$IS_OPEN_SOURCE_RELEASE_CANDIDATE) > push image to private GitLab registry"
+        echo "Closed-source release candidate > push image to private GitLab registry"
         export DOCKER_IMAGE_NAME=$CI_REGISTRY_IMAGE
         export TARGET_CI_REGISTRY=$CI_REGISTRY
         export TARGET_CI_REGISTRY_USER=$CI_REGISTRY_USER
         export TARGET_CI_REGISTRY_PASSWORD=$CI_REGISTRY_PASSWORD
       fi
-    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $TARGET_CI_REGISTRY
+    - docker login -u $TARGET_CI_REGISTRY_USER -p $TARGET_CI_REGISTRY_PASSWORD $TARGET_CI_REGISTRY
     - export DOCKER_IMAGE_NAME_FULL=$DOCKER_IMAGE_NAME:$CM_VERSION
     - docker tag $DOCKER_TMP_IMAGE_NAME $DOCKER_IMAGE_NAME_FULL
     - docker push $DOCKER_IMAGE_NAME_FULL
@@ -154,25 +151,15 @@ publish-docker-image:
     # cleaning up images
     - docker rmi $DOCKER_IMAGE_NAME_FULL $DOCKER_TMP_IMAGE_NAME
 
-# create-release:
-#   stage: publish
-#   image: registry.gitlab.com/gitlab-org/release-cli:latest
-#   rules:
-#     - if: $CI_COMMIT_TAG
-#   needs:
-#     - job: publish-jar
-#       artifacts: false
-#     - job: make-version-name
-#       artifacts: true
-#     - job: publish-docker-image
-#       artifacts: false
-#   release:
-#     tag_name: '$CI_COMMIT_TAG'
-#     name: 'Release $CI_COMMIT_TAG'
-#     description: > 
-#       This is an automated release generated for tag '$CI_COMMIT_TAG'
-#       Docker image: ${CI_REGISTRY_IMAGE}/core-eet:${CM_VERSION_NAME}
-#       Jar file: TODO
-#   script:
-#     - source .env
-#     - echo "creating a release" 
+publish-jar:
+  stage: publish
+  image: alpine:latest
+  rules:
+    - if: $CI_COMMIT_TAG
+  needs:
+    - job: make-version-name
+      artifacts: true
+    - job: build-jar
+      artifacts: true
+  script:
+    - echo "TODO upload somehwere"
