ci: clean pipeline

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -13,9 +13,16 @@ variables:
   MONGO_INITDB_ROOT_USERNAME: mongoadmin
   MONGO_INITDB_ROOT_PASSWORD: secret
   MONGO_INITDB_DATABASE: cytomine
-  
+  DOCKER_TMP_IMAGE_NAME: $CI_PIPELINE_ID:latest
+  DOCKER_TMP_JAR_IMAGE_NAME: $CI_PIPELINE_ID-jar-builder:latest
+
+# variable to register in project:
+# - SCRIPTS_REPO_ACCESS_TOKEN_NAME: access token name for docker-entrypoint-scripts repo
+# - SCRIPTS_REPO_ACCESS_TOKEN_VALUE: access token value for docker-entrypoint-scripts repo
+# - SCRIPTS_REPO_URL: git url (no scheme/protocol) of the docker-entrypoint-scripts repo
+
 default:
-  tags: 
+  tags:
     - docker
 
 make-version-name:
@@ -23,15 +30,15 @@ make-version-name:
   # regex check does not work with /bin/sh because of parenthesis so we need /bin/bash here
   image: bash:5.2.15-alpine3.16
   script:
-    - if [[ "$CI_COMMIT_REF_NAME" =~ ^refs/tags/ ]] && [[ "$CI_COMMIT_TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]]; then
-        echo "CM_VERSION_NAME=$CI_COMMIT_TAG" > .env;
+    - if [[ "$CI_COMMIT_REF_NAME" =~ ^refs/tags/ ]] then
+        echo "CM_VERSION=$CI_COMMIT_TAG" > .env;
       else
-        echo "CM_VERSION_NAME=$CI_COMMIT_SHORT_SHA-$(date '+%Y%m%d%H%M%S')-SNAPSHOT" > .env;
+        echo "CM_VERSION=$CI_COMMIT_SHORT_SHA-$(date '+%Y%m%d%H%M%S')-SNAPSHOT" > .env;
       fi
     - cat .env
   artifacts:
-    paths:
-      - .env
+    reports:
+      dotenv: .env
 
 run-junit:
   stage: test
@@ -52,6 +59,8 @@ run-junit:
     - "sed -i -- 's/port: 27018/port: 27017/g' src/test/resources/application.yml"
     - sed -i -- "s/127.0.0.1:390/ldap:389/g" src/test/resources/application.yml
     - sed -i -- "s/127.0.0.1:390/ldap:389/g" src/test/java/be/cytomine/security/LdapClientTests.java
+    # test log too large for gitlab if executed at 'debug' log level
+    - sed -i -- "s/name=\"be.cytomine\" level=\"debug\"/name=\"be.cytomine\" level=\"info\"/g" src/test/resources/logback-test.xml
     - gradle :test --no-daemon
   artifacts:
     reports:
@@ -60,25 +69,63 @@ run-junit:
 
 build-jar:
   stage: build
-  image: gradle:7.4.2-jdk17-alpine
+  image: docker:latest
   rules:
     - if: $CI_COMMIT_TAG
   needs:
+    # no dependence on junit tests success. This allow for build
+    # stage jobs to run in parallel with tests. If test fails,
+    # publish jobs are aborted
     - job: make-version-name
       artifacts: true
-    - job: run-junit
-      artifacts: false
   script:
-    - source .env
-    - export GRADLE_USER_HOME=$GRADLE_USER_HOME
-    - "sed -i -- 's/version: 0.0.0/version: '$CM_VERSION_NAME'/g' src/main/resources/application.yml"
-    - gradle bootJar --console=verbose
-    - mv build/libs/cytomine.jar build/libs/cytomine-$CM_VERSION_NAME.jar
+    - docker build --build-arg CORE_VERSION=$CM_VERSION -t $DOCKER_TMP_JAR_IMAGE_NAME -f docker/Dockerfile --target jar-builder .
+    - docker run --name $CI_PIPELINE_ID-builder-container -t $DOCKER_TMP_JAR_IMAGE_NAME
+    - mkdir -p build/libs/
+    - docker cp $CI_PIPELINE_ID-builder-container:/app/build/libs/cytomine.jar build/libs/cytomine-$CM_VERSION.jar
+  after_script:
+    - docker rm $CI_PIPELINE_ID-builder-container || true
+    - docker rmi $DOCKER_TMP_JAR_IMAGE_NAME
   artifacts:
     when: on_success
     expire_in: never
-    paths: 
+    paths:
       - build/libs/cytomine-*.jar
+
+build-docker-image:
+  stage: build
+  image: docker:latest
+  needs:
+    - job: build-jar
+      artifacts: false
+    - job: make-version-name
+      artifacts: true
+  rules:
+    - if: $CI_COMMIT_TAG
+  script:
+    - export SCRIPTS_REPO_FULL_URL=https://$SCRIPTS_REPO_ACCESS_TOKEN_NAME:$SCRIPTS_REPO_ACCESS_TOKEN_VALUE@$SCRIPTS_REPO_URL
+    - docker build --build-arg CORE_VERSION=$CM_VERSION --build-arg SCRIPTS_REPO_TAG=latest --secret id=scripts_repo_url,env=SCRIPTS_REPO_FULL_URL -t $DOCKER_TMP_IMAGE_NAME -f docker/Dockerfile .
+
+publish-docker-image:
+  stage: publish
+  image: docker:latest
+  needs:
+    - job: build-docker-image
+      artifacts: false  # artifact are in docker cache (is it a safe assumption in a multi-runner env ?)
+    - job: run-junit
+      artifacts: false
+    - job: make-version-name
+      artifacts: true
+  rules:
+    - if: $CI_COMMIT_TAG
+  script:
+    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
+    - export DOCKER_IMAGE_NAME_FULL=$CI_REGISTRY_IMAGE:$CM_VERSION
+    - docker tag $DOCKER_TMP_IMAGE_NAME $DOCKER_IMAGE_NAME_FULL
+    - docker push $DOCKER_IMAGE_NAME_FULL
+  after_script:
+    # cleaning up images
+    - docker rmi $DOCKER_IMAGE_NAME_FULL $DOCKER_TMP_IMAGE_NAME
 
 publish-jar:
   stage: publish
@@ -93,30 +140,11 @@ publish-jar:
   script:
     - echo "TODO upload somehwere"
 
-publish-docker-image:
-  stage: publish
-  image: docker:latest
-  needs:
-    - job: make-version-name
-      artifacts: true
-    - job: run-junit
-      artifacts: false
-  script:
-    - source .env
-    - export SCRIPTS_REPO_FULL_URL=https://${SCRIPTS_REPO_ACCESS_TOKEN_NAME}:${SCRIPTS_REPO_ACCESS_TOKEN_VALUE}@${SCRIPTS_REPO_URL}
-    - export DOCKER_IMAGE_NAME_FULL=${CI_REGISTRY_IMAGE}/core-eet:${CM_VERSION_NAME}
-    - echo ${SCRIPTS_REPO_FULL_URL}
-    - docker build --build-arg CORE_VERSION=${CM_VERSION_NAME} --build-arg SCRIPTS_REPO_TAG=latest --secret id=scripts_repo_url,env=SCRIPTS_REPO_FULL_URL -t ${DOCKER_IMAGE_NAME_FULL} -f docker/Dockerfile .
-    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
-    - docker push ${DOCKER_IMAGE_NAME_FULL}
-    # cleaning up
-    - docker rmi ${DOCKER_IMAGE_NAME_FULL}
-
 create-release:
   stage: publish
   image: registry.gitlab.com/gitlab-org/release-cli:latest
   rules:
-    - if: $CI_COMMIT_TAG
+    - if: $CI_COMMIT_TAG != null && $CI_COMMIT_TAG =~ /^ee[trd]-.*$/
   needs:
     - job: publish-jar
       artifacts: false
@@ -127,10 +155,10 @@ create-release:
   release:
     tag_name: '$CI_COMMIT_TAG'
     name: 'Release $CI_COMMIT_TAG'
-    description: > 
-      This is an automated release generated for tag '$CI_COMMIT_TAG'
-      Docker image: ${CI_REGISTRY_IMAGE}/core-eet:${CM_VERSION_NAME}
-      Jar file: TODO
+    # TODO add jar link
+    description: >
+      ## Release $CI_COMMIT_TAG
+
+      Docker image: $CI_REGISTRY_IMAGE:$CM_VERSION_NAME
   script:
-    - source .env
-    - echo "creating a release" 
+    - echo "Creating a release"
